### ISSUE TITLE
change layout

### ISSUE THREAD

**Issue by kerasus** [kerasus/Question-making-panel#800]

**Comment by JasGH** [comment]
- [ ] add layoutConfig to Routes object (by adding a boot file)
- [ ]  dispatch config value for each route
- [ ]  handle layoutConfig in store

**Comment by JasGH** [comment]
layoutConfig: {
        appBarVisibility: false,
        appBarType: 'A',
        sideBarVisibility: false,
        sideBarType: 'A'
      }

**Comment by Nima0mr** [comment]
THE WAY TO USE THE CONFIG IN BOOT:
this.$store.dispatch('AppLayout/updateTemplateHeaderType', {
          headerVisibility: false,
          headerType: 'A',
          sideBarVisibility: false,
          sideBarType: 'A'
        })
        this.$store.commit('AppLayout/updateTemplateHeaderType', this.$route.name)

**Comment by Nima0mr** [comment]
[Test.zip](https://github.com/kerasus/Question-making-panel/files/9389036/Test.zip)

**Comment by JasGH** [comment]
> [Test.zip](https://github.com/kerasus/Question-making-panel/files/9389036/Test.zip)

layoutConfig in store
