### ISSUE TITLE
متدهای مدل کارت نیاز به ادیت دارد

### ISSUE THREAD

**Issue by MaryamRazmjoo** [kerasus/Question-making-panel#836]
بعد از تغییر مدل کارت؛متدها تغییر نکرده اند و  بر روی اکشن های استور کارت تاثیر گذاشته است

**Comment by MaryamRazmjoo** [comment]
@JasGH

**Comment by JasGH** [comment]
ادیت اولیه انجام شد و به برنچ اصلی فرستاده شد.
