### ISSUE TITLE
کانفیگ لی اوت یوزر

### ISSUE THREAD

**Issue by MaryamRazmjoo** [kerasus/Question-making-panel#862]

**Comment by MaryamRazmjoo** [comment]
لی اوت فیگما
![Image](https://user-images.githubusercontent.com/79858155/188313843-0bd36636-f6a0-450b-ae65-7a79237c0a85.png)


لی اوت حاضر:


![Image](https://user-images.githubusercontent.com/79858155/188313879-fbb6f9ac-b262-4685-b572-d81834574db6.png)

**Comment by JasGH** [comment]
در کد حال حاضر کانفیگ لی اوت عوض شد و مشکلی دیده نشد :

![image](https://user-images.githubusercontent.com/81778219/189478039-29ed114e-feaa-4a94-826b-60df22170b06.png)

**Comment by Ayhanemoon** [comment]
the user layout still has problem, please fix it again
